### ISSUE TITLE
Work on 2.9.0

### ISSUE THREAD

**Issue by SeAmenLoo** [kromar/blender_Material_Brush#2]
2changes
1
     'blender': (2, 90, 0),
2
    brushstroke = {
            "name": "defaultStroke",
            "pen_flip": False,
            "is_start": False,
            "location": (0,0,0),
            "mouse": (x, y),
            #"mouse_event": (0.0, 0.0),
            "pressure": 1,
            "size": bpy.context.tool_settings.unified_paint_settings.size,
            "time": self.time,
            #"x_tilt": 0,
            #"y_tilt": 0
            }
it works but i dont know why
ps: how to undo the stroke of all layers by one step？

**Comment by kromar** [comment]
i did not get the first part, is that a question?

i think at the moment you need to use undo as many times as texture channels are set up to undo all or use undo history (no clue why the keybinding was removed) to jump back.

**Comment by SeAmenLoo** [comment]
thanks
the first part is what i did to make the plugin work on 2.9.0.
i just change the version and fix the error ,but i dont know the reason why i have to remove the "mouse_event"and"x_tilt" lines.

about the undo part,thanks for you advice about undo history
and i will try some coding way to undo all texture channels by one hotkey.

**Comment by kromar** [comment]
i think the mouse event and tilt are recent additions and might not have been added before 2.92.

feel free to open some pull request if you do some fixes, i dont know when/if im going to invest more time into this addon.

**Comment by kromar** [comment]
i uploaded a fix for what you reported, so all versions above 2.91 will have the extra stroke options. they have been added in 2.91
